// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eAByoDsCA_1M3VxQMX54iAmo4O_20lU',
    appId: '1:765257070561:web:2d616407b28e36071904a0',
    messagingSenderId: '765257070561',
    projectId: 'noticeboard-1afde',
    authDomain: 'noticeboard-1afde.firebaseapp.com',
    databaseURL: 'https://noticeboard-1afde-default-rtdb.firebaseio.com',
    storageBucket: 'noticeboard-1afde.appspot.com',
    measurementId: 'G-76QJL4BR6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AZWBBv1ugmZgFFyqEvHH4WueP6CIi3U',
    appId: '1:765257070561:android:f363da52e80197721904a0',
    messagingSenderId: '765257070561',
    projectId: 'noticeboard-1afde',
    databaseURL: 'https://noticeboard-1afde-default-rtdb.firebaseio.com',
    storageBucket: 'noticeboard-1afde.appspot.com',
  );
}
